name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  call-dockerhub-action:
    uses: NelsonDane/DockerHub-Actions/.github/workflows/dockerhub-description.yml@2f832df9dadc9af66cccda7e61fedd715b1cb0a3
    with:
      dockerhub_repo_name: auto-rsa
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
