name: Docker Build and Push

on:
  push:
    branches:
      - 'main'
      - 'develop*'

jobs:
  call-workflow-dockerhub-build-push:
    uses: NelsonDane/DockerHub-Actions/.github/workflows/dockerhub_build_push.yml@2f832df9dadc9af66cccda7e61fedd715b1cb0a3
    with:
      image_name: auto-rsa
      image_tag: ${{ github.ref_name == 'main' && 'latest' || startsWith(github.ref_name, 'develop') && github.ref_name }}
      should_push: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'develop') }}
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
